# These are supported funding model platforms

patreon: mehedimi
open_collective: # Replace with a single Open Collective username
ko_fi: mehedimi
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: mehedimi
issuehunt: mehedimi
otechie: mehedimi
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
