<?php

namespace Mehedi\LaravelDynamoDB\Eloquent;

class Model extends \Illuminate\Database\Eloquent\Model
{
    public $incrementing = false;

    public function update(array $attributes = [], array $options = [])
    {
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }
}